import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1000, height: 900 } });
const logs=[];
p.on('console', m => { const t=m.text(); if(t.includes('[MIDAS]')) logs.push(t); });
p.on('pageerror', e => logs.push('ERR '+e.message));
await p.goto('http://localhost:8123/', { waitUntil:'networkidle' });
await p.evaluate(()=>document.getElementById('about')?.scrollIntoView({block:'center'}));
await p.waitForTimeout(4500);
console.log(logs.join('\n')||'no midas logs');
await b.close();
