import { chromium } from '@playwright/test';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 }, reducedMotion: 'reduce' });
const p = await ctx.newPage();
await p.goto('http://localhost:8123/', { waitUntil: 'networkidle' });
await p.waitForTimeout(1500);
await p.evaluate(() => document.getElementById('play')?.scrollIntoView({ block: 'center' }));
await p.waitForTimeout(3500);
const txt = await p.evaluate(() => document.querySelector('#play')?.innerText?.includes('SCROLL') || document.querySelector('#play')?.innerText?.includes('Scroll'));
const canvases = await p.evaluate(() => document.querySelectorAll('#play canvas').length);
console.log('reduced-motion -> play canvases:', canvases, '| still showing scroll hint:', txt);
await b.close();
